/**
 * H2MS: Hand Hygiene Monitoring System
 * This is the draft API design for H2MS.
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface ComplianceReport {
    name?: string;
    /**
     * Hand washing opportunities
     */
    opportunities?: number;
    /**
     * Hand washing events taken
     */
    events?: number;
    /**
     * Compliance percentage
     */
    compliance?: number;
}
