/**
 * H2MS: Hand Hygiene Monitoring System
 * This is the draft API design for H2MS.
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface Location {
    id?: number;
    name: string;
    type: string;
    address?: string;
    city?: string;
    stateOrProvince?: string;
    country?: string;
    zip?: string;
    parent?: Location;
    children?: Array<Location>;
}
