/**
 * H2MS: Hand Hygiene Monitoring System
 * This is the draft API design for H2MS.
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import {Location} from './location';
import {UserType} from './userType';


export interface User {
    id?: number;
    firstName: string;
    middleName?: string;
    lastName: string;
    email: string;
    notificationFrequency?: string;
    type: UserType;
    location?: Location;
    photo?: string;
    isAdmin?: boolean;
}
